### ISSUE TITLE
I'm getting many question marks..

### ISSUE THREAD

**Issue by liormagen** [kyokomi/emoji#10]
I think that some of the emojis I try to convert using the emoji library are being converted to question marks.

Any chance it happens as a result of the emojis that comes with iOS 10 maybe?

**Comment by bep** [comment]
Not sure why I watch this repo ... but this repo ourproduces valid unicode emojis, so I would have a look at your client.

**Comment by liormagen** [comment]
It's not an issue with the emoji conversion but with the emoji detection.
