### ISSUE TITLE
Support GitHub custom emoji?

### ISSUE THREAD

**Issue by KrazyCavin** [kyokomi/emoji#13]
Hi kyokomi,

It seams the emojis are mapped to unicode. Some custom emojis of GitHub are missing, like :octocat: :neckbeard: ... Is it possible to support these custom emoji, generated from image?https://github.com/github/gemoji/tree/master/images

**Comment by kyokomi** [comment]
I'm sorry. 🙏 
Because code is generated based on correspondence table of this emoji and Unicode, emoji which does not exist here does not correspond.

https://raw.githubusercontent.com/github/gemoji/master/db/emoji.json

**Comment by KrazyCavin** [comment]
@kyokomi 😢 but thanks!
