### ISSUE TITLE
Updated Emoji list?

### ISSUE THREAD

**Issue by Jayphen** [kyokomi/emoji#20]
The [Github emoji cheatsheet](https://www.webpagefx.com/tools/emoji-cheat-sheet/) is quite outdated now. Is there a more-recent reference anywhere online?

**Comment by kyokomi** [comment]
I'm sorry I don't know :bow: Since I am referring to this, if you want to know the latest, you can refer to here.
https://github.com/github/gemoji

**Comment by CodeFreezr** [comment]
Find here one for emoji v5: https://github.com/CodeFreezr/emojo/tree/master/db/v5.

**Comment by kyokomi** [comment]
@CodeFreezr Thanks.

Fixed https://github.com/kyokomi/emoji/pull/27
