### ISSUE TITLE
tags are not semver

### ISSUE THREAD

**Issue by rsc** [kyokomi/emoji#23]
Hi,

Semver and vgo require 3-number tags, like v1.2.0 not v1.2. The tags in this repo like v1.5, v1.4, etc do not conform and are therefore not semver and are therefore ignored by vgo. Instead vgo will use the latest semver-conforming tag, the much older v0.0.2.

I would suggest tagging a new v1.5.1 or v1.6.0 for use with vgo and using three-number tags for future tags. Obviously the existing tags should be left alone since no doubt some other systems are using them. 

See also https://github.com/gohugoio/hugo/pull/4754/commits/14649127a812e787323be5a564d39db51531e19d, which worked around the fact that v0.0.2 was the last semver-compatible tag.

Thanks.

**Comment by kyokomi** [comment]
@rsc Thank you.
I made a tag of v1.5.1. https://github.com/kyokomi/emoji/releases/tag/v1.5.1

:bow:
