### ISSUE TITLE
Heart emoji is showing as black. Needs two code points

### ISSUE THREAD

**Issue by braderhart** [kyokomi/emoji#34]
See here:

https://en.wikipedia.org/wiki/Heart_symbol#Encoding

The emoji heart should be `\u2764\ufe0f`.

**Comment by kyokomi** [comment]
@braderhart Thank you for the report.

Since it is generated with reference to [here](http://www.unicode.org/emoji/charts/emoji-list.html#2764), it cannot be supported.
