### ISSUE TITLE
[request] Update the emoji codemap for the latest unicode v14.0

### ISSUE THREAD

**Issue by kaushalmodi** [kyokomi/emoji#53]
Hello,

Can you please update the emoji code map in this package so that it uses all the latest emojis.

I am using this package through Hugo (https://gohugo.io).

Thanks!

**Comment by kyokomi** [comment]
@kaushalmodi Thanks for the issue. Updated. https://github.com/kyokomi/emoji/releases/tag/v2.2.9

**Comment by kaushalmodi** [comment]
Thanks a lot!
