### ISSUE TITLE
missing glyphs or...

### ISSUE THREAD

**Issue by gour** [kyokomi/emoji#9]
Hello, 

I'd like to use emojis in Hugo, but when I execute `hello.go` test file in the terminal I get the following:

```
Hello World Emoji!
🍺  Beer!!!
I like a 🍕  and 🍣 !!
```

so I wonder if some font has to be installed in order to get proper glyphs displayed?

**Comment by kyokomi** [comment]
I'm sorry, I do not understand the situation a bit ...
Perhaps your terminal does not support unicode?

**Comment by gour** [comment]
> Perhaps your terminal does not support unicode?

I'm using Gnome Terminal which does support Unicode..however, I do use neither Go nor Hugo any longer, so you can close it.

**Comment by kyokomi** [comment]
🙏
